openapi: 3.0.0
info:
  title: GetFacts
  version: 1.0.0
servers:
  - url: https://catfact.ninja
paths:
  /fact:
    get:
      tags:
        - default
      summary: GetCatFact
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          content:
           application/json:
              schema:
                $ref: "#/components/schemas/catfact"
components:
  schemas:
    CatFacts:
      x-flow-type:
		  description: Get cat facts	
          name: CatFacts
      x-flow-query:
        path: /fact
        operation: get
	     title: GetCatFact
       type: object
      properties:
        Fact:
          type: string
        Length:
          type: integer