openapi: 3.0.0
info:
  title: TestAPIs
  version: 1.0.0
servers:
  - url: https://catfact.ninja
paths:
  /fact:
    get:
      tags:
        - default
      summary: GetCatFact
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          content:
           application/json:
              schema:
                $ref: "#/components/schemas/catfact"
          description: OK
components:
  schemas:
    catfact:
      x-flow-type:
          name: catfact
      x-flow-query:
          path: /fact
          operation: get    
      properties:
        fact:
          type: string
        length:
          type: integer
