openapi: 3.0.0
info:
  title: GetFact
  version: 1.0.0
servers:
  - url: https://catfact.ninja
paths:
  /fact:
    get:
      tags:
        - default
      summary: GetCatFact
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          content:
           application/json:
              schema:
                $ref: "#/components/schemas/CatFact"
components:
  schemas:
    CatFact:
      x-flow-type:
        name: GetFact
      x-flow-query:
        path: /fact
        operation: get
      type: object
      properties:
        length:
          type: integer
        fact:
          type: string